/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

import services.ServicesLocator;

/**
 *
 * @author HP 11na
 */
public class DialogDuracionLiga extends javax.swing.JDialog {

    public DialogDuracionLiga(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        lblError.setVisible(false);
        lblErrorIni.setVisible(false);

        ArrayList<String> list = ServicesLocator.getEstadioServices().obtenerNombresEstadios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFechaInicio = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DateChooserFechaInicio = new com.toedter.calendar.JDateChooser();
        DateChooserFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabelFechaFinal = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblErrorIni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(700, 250, 231, 231));
        setMinimumSize(new java.awt.Dimension(588, 231));
        setResizable(false);
        setSize(new java.awt.Dimension(588, 231));

        jLabelFechaInicio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFechaInicio.setText("Fecha de inicio");

        jButtonIniciar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIniciar.setText("Comenzar liga");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setText("Establezca el rango de fechas para la temporada de la Liga:");

        DateChooserFechaInicio.setDate(new Date());
        DateChooserFechaInicio.setDateFormatString("yyyy-MM-dd");
        DateChooserFechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateChooserFechaInicioPropertyChange(evt);
            }
        });

        DateChooserFechaFinal.setDateFormatString("yyyy-MM-dd");
        DateChooserFechaFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateChooserFechaFinalPropertyChange(evt);
            }
        });

        jLabelFechaFinal.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelFechaFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFechaFinal.setText("Fecha de culminación");

        lblError.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 51));
        lblError.setText("Ha ingresado incorrectamente una de las fechas o ha dejado un campo vacío");

        lblErrorIni.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblErrorIni.setForeground(new java.awt.Color(204, 0, 51));
        lblErrorIni.setText("La fecha de inicio debe ser antes que la de culminación");

<<<<<<< HEAD
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonIniciar)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DateChooserFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DateChooserFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblErrorIni, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelFechaInicio))
                    .addComponent(DateChooserFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelFechaFinal))
                    .addComponent(DateChooserFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorIni)
                .addGap(46, 46, 46))
        );
=======
        jLabel2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\visual\\images\\4 (1).png")); // NOI18N
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 270));
>>>>>>> 33abc59 (direccion_images)

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        try {
            Date inicio = DateChooserFechaInicio.getDate();
            Date fin = DateChooserFechaFinal.getDate();

            if (fin.compareTo(inicio) > 0) {
                ServicesLocator.getIntervaloFServices().establecerIntervalo(inicio, fin);

                JOptionPane.showMessageDialog(null, "La Liga Nacional de Fútbol ha comenzado", "Atención", 1);

                // // ServicesLocator.getPartidoServices().limpiarPartidos(); // elimina todos los partidos anteriores registrados

                dispose();
            } else {
                lblErrorIni.setVisible(true);
            }
        } catch (Exception e) {
            lblError.setVisible(true);
        }
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void DateChooserFechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateChooserFechaInicioPropertyChange
        lblError.setVisible(false);
        lblErrorIni.setVisible(false);
    }//GEN-LAST:event_DateChooserFechaInicioPropertyChange

    private void DateChooserFechaFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateChooserFechaFinalPropertyChange
        lblError.setVisible(false);
        lblErrorIni.setVisible(false);
    }//GEN-LAST:event_DateChooserFechaFinalPropertyChange

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>
    //     /* Create and display the dialog */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             RPartidosEquipos dialog = new RPartidosEquipos(new javax.swing.JFrame(), true);
    //             dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    //                 @Override
    //                 public void windowClosing(java.awt.event.WindowEvent e) {
    //                     System.exit(0);
    //                 }
    //             });
    //             dialog.setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserFechaFinal;
    private com.toedter.calendar.JDateChooser DateChooserFechaInicio;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFechaFinal;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblErrorIni;
    // End of variables declaration//GEN-END:variables
}
