/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import java.sql.SQLException;

import javax.swing.JFrame;

import model.Rol;
import model.Usuario;
import services.ServicesLocator;

/**
 *
 * @author HP 11na
 */
public class Login extends javax.swing.JDialog {

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        lblErrorUs.setVisible(false);
        lblErrorCont.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        lblCont = new javax.swing.JLabel();
        lblErrorUs = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblErrorCont = new javax.swing.JLabel();
        lblTit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio de sesión");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(143, 182, 155));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        tfUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tfUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel1.add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        passwordField.setBackground(new java.awt.Color(255, 255, 255));
        passwordField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, -1));

        lblCont.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblCont.setForeground(new java.awt.Color(0, 0, 0));
        lblCont.setText("Contraseña");
        jPanel1.add(lblCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        lblErrorUs.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblErrorUs.setForeground(new java.awt.Color(0, 102, 102));
        lblErrorUs.setText("Usuario incorrecto");
        lblErrorUs.setToolTipText("");
        jPanel1.add(lblErrorUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnIniciar.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciar.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        lblErrorCont.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblErrorCont.setForeground(new java.awt.Color(0, 102, 102));
        lblErrorCont.setText("Contraseña incorrecta");
        jPanel1.add(lblErrorCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblTit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblTit.setForeground(new java.awt.Color(0, 0, 0));
        lblTit.setText("Ingrese sus datos:");
        jPanel1.add(lblTit, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnIniciarActionPerformed
        try {
            lblErrorUs.setVisible(false);
            lblErrorCont.setVisible(false);
            Usuario us = ServicesLocator.getUsuarioServices().getByNombreUsuario(tfUsuario.getText());
            if (us != null) {
                if (ServicesLocator.getUsuarioServices().verificarContrasena(us.getNombreUsuario(),
                        new String(passwordField.getPassword()))) {
                    if (us.getRol().equals(Rol.gestor_liga.toString())) {
                        Principal.rol = Rol.gestor_liga;
                    } else {
                        Principal.rol = Rol.gestor_usuario;
                    }

                    dispose();
                } else {
                    lblErrorCont.setVisible(true);
                }
            } else {
                lblErrorUs.setVisible(true);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }// GEN-LAST:event_btnIniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCont;
    private javax.swing.JLabel lblErrorCont;
    private javax.swing.JLabel lblErrorUs;
    private javax.swing.JLabel lblTit;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
