/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import javax.swing.JFrame;

/**
 *
 * @author HP 11na
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setSize(800, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        menuBar = new javax.swing.JMenuBar();
        menuGestion = new javax.swing.JMenu();
        menuItemEstadios = new javax.swing.JMenuItem();
        menuItemEquipos = new javax.swing.JMenuItem();
        menuItemPartidos = new javax.swing.JMenuItem();
        menuItemFutbolistas = new javax.swing.JMenuItem();
        menuItemPosJug = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuItemReportes = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de la Liga Nacional de Fútbol");
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuGestion.setText("CRUDs");

        menuItemEstadios.setLabel("Estadios");
        menuItemEstadios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEstadiosActionPerformed(evt);
            }
        });
        menuGestion.add(menuItemEstadios);

        menuItemEquipos.setLabel("Equipos");
        menuItemEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEquiposActionPerformed(evt);
            }
        });
        menuGestion.add(menuItemEquipos);

        menuItemPartidos.setLabel("Partidos");
        menuItemPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPartidosActionPerformed(evt);
            }
        });
        menuGestion.add(menuItemPartidos);

        menuItemFutbolistas.setLabel("Futbolistas");
        menuItemFutbolistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFutbolistasActionPerformed(evt);
            }
        });
        menuGestion.add(menuItemFutbolistas);

        menuItemPosJug.setText("Cambiar Pos. Jugador");
        menuGestion.add(menuItemPosJug);

        menuBar.add(menuGestion);

        menuReportes.setLabel("Reportes");

        menuItemReportes.setActionCommand("Reportes");
        menuItemReportes.setLabel("Generar Reportes");
        menuItemReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReportesActionPerformed(evt);
            }
        });
        menuReportes.add(menuItemReportes);

        menuBar.add(menuReportes);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemEstadiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEstadiosActionPerformed
        CrudEstadio dialog = new CrudEstadio(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemEstadiosActionPerformed

    private void menuItemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemReportesActionPerformed

    private void menuItemEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEquiposActionPerformed

    private void menuItemPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPartidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemPartidosActionPerformed

    private void menuItemFutbolistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFutbolistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemFutbolistasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenuItem menuItemEquipos;
    private javax.swing.JMenuItem menuItemEstadios;
    private javax.swing.JMenuItem menuItemFutbolistas;
    private javax.swing.JMenuItem menuItemPartidos;
    private javax.swing.JMenuItem menuItemPosJug;
    private javax.swing.JMenuItem menuItemReportes;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
