/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import java.sql.SQLException;
import java.util.ArrayList;

import services.EquipoServices;
import services.PartidoServices;
import services.ServicesLocator;

/**
 *
 * @author HP 11na
 */
public class REstadoEquipo extends javax.swing.JDialog {

    /**
     * Creates new form RPartidosEquipos
     */
    public REstadoEquipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ArrayList<String> list = ServicesLocator.getEquipoServices().obtenerNombresEquipos();

        for (String s : list) {
            ComboBoxEquipo.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTit = new javax.swing.JLabel();
        ComboBoxEquipo = new javax.swing.JComboBox<>();
        jLabelEquipo = new javax.swing.JLabel();
        jButtonGeneraR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTit.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabelTit.setText("Seleccione el equipo para ver su estado:");
        getContentPane().add(jLabelTit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 396, 37));

        ComboBoxEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabelEquipo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelEquipo.setText("Equipo");
        getContentPane().add(jLabelEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jButtonGeneraR.setBackground(new java.awt.Color(59, 122, 26));
        jButtonGeneraR.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButtonGeneraR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGeneraR.setText("Generar Reporte");
        jButtonGeneraR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeneraRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGeneraR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 141, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon("src\\main\\java\\visual\\images\\Diseño sin título (3) (2).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\visual\\images\\5 (3).png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEquipoActionPerformed
    }//GEN-LAST:event_ComboBoxEquipoActionPerformed

    private void jButtonGeneraRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeneraRActionPerformed
        int contenidoComboBox = ComboBoxEquipo.getSelectedIndex();
        
        ServicesLocator.getEquipoServices().reporteEstadoEquipo(contenidoComboBox);

        dispose();
    }//GEN-LAST:event_jButtonGeneraRActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosPorEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosPorEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosPorEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosPorEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the dialog */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             RPartidosPorEquipos dialog = new RPartidosPorEquipos(new javax.swing.JFrame(), true);
    //             dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    //                 @Override
    //                 public void windowClosing(java.awt.event.WindowEvent e) {
    //                     System.exit(0);
    //                 }
    //             });
    //             dialog.setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxEquipo;
    private javax.swing.JButton jButtonGeneraR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEquipo;
    private javax.swing.JLabel jLabelTit;
    // End of variables declaration//GEN-END:variables
}
