/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import services.EquipoServices;
import services.PartidoServices;
import services.ServicesLocator;

/**
 *
 * @author HP 11na
 */
public class RPartidosPorEquipos extends javax.swing.JDialog {

    /**
     * Creates new form RPartidosEquipos
     */
    public RPartidosPorEquipos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ArrayList<String> list = ServicesLocator.getEquipoServices().obtenerNombresEquipos();

        for (String s : list) {
            ComboBoxEquipo1.addItem(s);
            ComboBoxEquipo2.addItem(s);
        }

        ComboBoxEquipo2.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTit = new javax.swing.JLabel();
        ComboBoxEquipo1 = new javax.swing.JComboBox<>();
        jLabelEquipo1 = new javax.swing.JLabel();
        ComboBoxEquipo2 = new javax.swing.JComboBox<>();
        jLabelEquipo2 = new javax.swing.JLabel();
        jButtonGeneraR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTit.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabelTit.setText("Seleccione dos Equipos");
        getContentPane().add(jLabelTit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 270, 37));

        ComboBoxEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEquipo1ActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 87, -1, -1));

        jLabelEquipo1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelEquipo1.setText("Equipo # 1");
        getContentPane().add(jLabelEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 90, -1, -1));

        getContentPane().add(ComboBoxEquipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 164, -1, -1));

        jLabelEquipo2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelEquipo2.setText("Equipo # 2");
        getContentPane().add(jLabelEquipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 167, -1, -1));

        jButtonGeneraR.setBackground(new java.awt.Color(59, 122, 26));
        jButtonGeneraR.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButtonGeneraR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGeneraR.setText("Generar Reporte");
        jButtonGeneraR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeneraRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGeneraR, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 141, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ALMACEN\\Proyectos Java\\New folder\\Liga\\src\\main\\java\\visual\\images\\VerPartidos.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ALMACEN\\Proyectos Java\\New folder\\Liga\\src\\main\\java\\visual\\images\\5 (4).png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ComboBoxEquipo1ActionPerformed
    }// GEN-LAST:event_ComboBoxEquipo1ActionPerformed

    private void jButtonGeneraRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonGeneraRActionPerformed
        int contenidoComboBox1 = ComboBoxEquipo1.getSelectedIndex();
        int contenidoComboBox2 = ComboBoxEquipo2.getSelectedIndex();
        if (contenidoComboBox1 != contenidoComboBox2) {
            ServicesLocator.getPartidoServices().reportePartidosPorEquipos(contenidoComboBox1, contenidoComboBox2);

            dispose();
        } else
            JOptionPane.showMessageDialog(null, "Debe seleccionar 2 equipos diferentes.",
                    "Aviso", JOptionPane.ERROR_MESSAGE);

    }// GEN-LAST:event_jButtonGeneraRActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(RPartidosPorEquipos.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(RPartidosPorEquipos.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(RPartidosPorEquipos.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(RPartidosPorEquipos.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>

    // /* Create and display the dialog */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // RPartidosPorEquipos dialog = new RPartidosPorEquipos(new
    // javax.swing.JFrame(), true);
    // dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    // @Override
    // public void windowClosing(java.awt.event.WindowEvent e) {
    // System.exit(0);
    // }
    // });
    // dialog.setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxEquipo1;
    private javax.swing.JComboBox<String> ComboBoxEquipo2;
    private javax.swing.JButton jButtonGeneraR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEquipo1;
    private javax.swing.JLabel jLabelEquipo2;
    private javax.swing.JLabel jLabelTit;
    // End of variables declaration//GEN-END:variables
}
