/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import model.Estadio;
import model.Partido;

import services.EquipoServices;
import services.EstadioServices;
import services.PartidoServices;
import services.ServicesLocator;

/**
 *
 * @author HP 11na
 */
public class RPartidosPorFecha extends javax.swing.JDialog {

    public RPartidosPorFecha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ArrayList<String> list = ServicesLocator.getEstadioServices().obtenerNombresEstadios();
        
        ComboBoxEstadio.addItem("Todos");
        
        for (String s : list) {
            ComboBoxEstadio.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFecha = new javax.swing.JLabel();
        ComboBoxEstadio = new javax.swing.JComboBox<>();
        jLabelEstadio = new javax.swing.JLabel();
        jButtonGeneraR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFecha.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelFecha.setText("Fecha del partido");
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, -1, -1));

        ComboBoxEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEstadioActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxEstadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 131, -1, -1));

        jLabelEstadio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabelEstadio.setText("Estadio");
        getContentPane().add(jLabelEstadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 134, -1, -1));

        jButtonGeneraR.setBackground(new java.awt.Color(59, 122, 26));
        jButtonGeneraR.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButtonGeneraR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGeneraR.setText("Generar Reporte");
        jButtonGeneraR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeneraRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGeneraR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 149, 33));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel1.setText("Seleccione una fecha y estadio y se mostraran los partidos correspondientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 420, -1));

        DateChooserFecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(DateChooserFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 62, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("src\\main\\java\\visual\\images\\Portería.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\visual\\images\\5 (4).png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 560, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGeneraRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeneraRActionPerformed
        
        Date fecha = DateChooserFecha.getDate();

        int index = ComboBoxEstadio.getSelectedIndex();
        
        ServicesLocator.getPartidoServices().reportePartidosPorFecha(fecha, index);
        
        dispose();
    }//GEN-LAST:event_jButtonGeneraRActionPerformed

    private void ComboBoxEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEstadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEstadioActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(RPartidosEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the dialog */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             RPartidosEquipos dialog = new RPartidosEquipos(new javax.swing.JFrame(), true);
    //             dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    //                 @Override
    //                 public void windowClosing(java.awt.event.WindowEvent e) {
    //                     System.exit(0);
    //                 }
    //             });
    //             dialog.setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxEstadio;
    private com.toedter.calendar.JDateChooser DateChooserFecha;
    private javax.swing.JButton jButtonGeneraR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEstadio;
    private javax.swing.JLabel jLabelFecha;
    // End of variables declaration//GEN-END:variables
}
